# Generated by Django 2.0.8 on 2020-04-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Courses',
        ),
    ]
